const TSNS_CONFIG = {
  LIFF_ID: "2010571742-kNZobt1U",
  GAS_API_URL: "PUT_TSNS_IAM_WEB_APP_EXEC_URL_HERE",
  DASHBOARD_URL: "PUT_TSNS_IAM_WEB_APP_EXEC_URL_HERE",
  VERSION: "Sprint 6.1.3",
  ENV: "DEV"
};
